//ASSETS
const assetUrl = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, "")}`;

export const ASSETS = {
    MODEL: assetUrl("models/billiards_assets.glb"),
    BASE_COLOR: assetUrl("textures/pool_table/BaseColor.png"),
    NORMAL: assetUrl("textures/pool_table/Normal.png"),
    ROUGHNESS: assetUrl("textures/pool_table/Roughness.png"),
    METALLIC: assetUrl("textures/pool_table/Metallic.png"),
    HEIGHT: assetUrl("textures/pool_table/Height.png")
};
export const PUB_ASSETS = {
    POOL_LIGHT: assetUrl("models/pub/pool_light.glb"),
    PUB_COUNTER: assetUrl("models/pub/pub_counter.glb"),
    BACK_BAR: assetUrl("models/pub/back_bar.glb"),
    FURNITURE: assetUrl("models/pub/furniture.glb"),
    BARREL: assetUrl("models/pub/barrel.glb"),
    ENTRANCE_DOOR: assetUrl("models/pub/entrance_door.glb"),
    PUB_WINDOW: assetUrl("models/pub/pub_window.glb"),
    JUKEBOX: assetUrl("models/pub/jukebox.glb"),
    BOTTLES: assetUrl("models/pub/bottles.glb"),
    WHISKEY_SET: assetUrl("models/pub/whiskey_set.glb"),
    WALL_CLOCK: assetUrl("models/pub/wall_clock.glb"),
    SCOREBOARD: assetUrl("models/pub/scoreboard.glb"),
    FLOOR_BASE_COLOR: assetUrl("textures/pub/floor_basecolor.jpg"),
    FLOOR_NORMAL: assetUrl("textures/pub/floor_normal.png"),
    FLOOR_ROUGHNESS: assetUrl("textures/pub/floor_roughness.png"),
    WALL_BASE_COLOR: assetUrl("textures/pub/wall_basecolor.jpg"),
    WALL_NORMAL: assetUrl("textures/pub/wall_normal.png"),
    WALL_ROUGHNESS: assetUrl("textures/pub/wall_roughness.jpg"),
    EXTERIOR_WALL_BASE_COLOR: assetUrl("textures/pub/exterior_wall_basecolor.jpg"),
    EXTERIOR_WALL_HEIGHT: assetUrl("textures/pub/exterior_wall_height.png"),
    EXTERIOR_FOREST_BACKDROP: assetUrl("textures/pub/exterior_forest_backdrop.jpg"),
    PANELS_BASE_COLOR: assetUrl("textures/pub/panels_basecolor.jpg"),
    PANELS_NORMAL: assetUrl("textures/pub/panels_normal.png"),
    PANELS_ROUGHNESS: assetUrl("textures/pub/panels_roughness.png")
};
export const PUB_ENVIRONMENT = {
    ROOM_WIDTH: 7.6,
    ROOM_DEPTH: 10.0,
    ROOM_HEIGHT: 3.65,
    WAINSCOT_HEIGHT: 1.06,
    TRIM_HEIGHT: 0.055,
    TRIM_DEPTH: 0.035,
    MAIN_TABLE_Z: 0.68,
    POOL_LIGHT_CENTER_Y: 3.05,
    POOL_LIGHT_SHADE_CENTERS_X: [
        -0.72,
        0.0,
        0.72
    ],
    POOL_LIGHT_BULB_LOCAL_Y: 0.050,
    POOL_LIGHT_EMITTER_LOCAL_Y: 0.070,
    BAR_COUNTER_Z: -2.95,
    BACK_BAR_Z: -4.76,
    BACK_BAR_RAISE_Y: 0.0,
    BACK_BAR_SCALE_Y: 1.28,
    LEFT_DINING_X: -2.62,
    LEFT_DINING_Z: 0.92,
    RIGHT_DINING_X: 2.88,
    RIGHT_DINING_Z: 0.42,
    DINING_TABLE_SEPARATION: 0.79,
    DINING_CHAIR_OFFSET: 0.70,
    LEFT_WINDOW_NOOK_X: 2.72,
    LEFT_WINDOW_NOOK_Z: 3.06,
    ENTRANCE_DOOR_OPENING_WIDTH: 2.82,
    ENTRANCE_DOOR_OPENING_HEIGHT: 2.34,
    ENTRANCE_DOOR_Z_INSET: 0.0,
    ENTRANCE_WINDOW_CENTERS_X: [
        -2.45,
        2.45
    ],
    ENTRANCE_WINDOW_FLOOR_Y: 1.05,
    ENTRANCE_WINDOW_OPENING_WIDTH: 1.18,
    ENTRANCE_WINDOW_OPENING_BOTTOM: 1.15,
    ENTRANCE_WINDOW_OPENING_HEIGHT: 1.05,
    ENTRANCE_WINDOW_Z_INSET: 0.0,
    FRONT_FACADE_TOP_BAND_BOTTOM: 2.50,
    JUKEBOX_X: -3.34,
    JUKEBOX_Z: 3.38,
    SCOREBOARD_BOTTOM_Y: 1.18,
    SCOREBOARD_Z: -0.92,
    WALL_CLOCK_BOTTOM_Y: 1.92,
    WALL_CLOCK_Z: 1.05,
    CUE_RACK_Z: -1.28,
    BACK_BAR_SHELF_Y: [
        0.84,
        1.19,
        1.54
    ],
    BACK_BAR_BOTTLE_Z: -4.73,
    COUNTER_PROP_Y: 1.114,
    BAR_COUNTER_TOP_Y: 1.100,
    BAR_DECOR_Y: 1.087,
    WHISKEY_SET_X: 1.38,
    WHISKEY_SET_Z: -2.76,
    COUNTER_RACK_X: -1.36,
    COUNTER_RACK_Z: -2.72,
    COUNTER_RUBBER_X: -1.02,
    COUNTER_RUBBER_Z: -2.69,
    SCOREBOARD_LIGHT_Y: 2.56,
    CUE_RACK_LIGHT_Y: 2.56,
    WALL_ACCENT_DISTANCE: 2.90,
    WALL_ACCENT_INTENSITY: 28,
    WALL_ACCENT_ANGLE: Math.PI / 4.0,
    WALL_ACCENT_PENUMBRA: 0.88,
    WINDOW_GLASS_WIDTH_FACTOR: 0.90,
    WINDOW_GLASS_HEIGHT_FACTOR: 0.90,
    WINDOW_GLASS_DEPTH_OFFSET: 0.0,
    EXTERIOR_FAR_Z: 8.35,
    EXTERIOR_GROUND_CENTER_Z: 7.05,
    FLOOR_REPEAT_X: 4.2,
    FLOOR_REPEAT_Z: 5.4,
    WALL_REPEAT_PER_METER: 0.52,
    PANEL_REPEAT_PER_METER: 0.50
};

//BALL PHYSICS
export const BALL = {
    DIAMETER: 0.05715,
    RADIUS: 0.028575,
    MASS: 0.17,
    INITIAL_YAW_DEG: 90
};

//CAMERA
export const CAMERA = {
    FOV: 45,
    NEAR: 0.01,
    FAR: 100
};
export const LIGHTING = {
    AMBIENT_INTENSITY: 0.35,
    TABLE_POINT_INTENSITIES: [
        22,
        25,
        22
    ],
    TABLE_POINT_DISTANCE: 3.35,
    TABLE_POINT_DECAY: 2.0,
    TABLE_POINT_SHADOW_MAP_SIZE: 512,
    TABLE_POINT_SHADOW_NEAR: 0.05,
    TABLE_POINT_SHADOW_FAR: 3.6,
    BAR_PENDANT_INTENSITY: 28,
    SIDE_PENDANT_INTENSITY: 22,
    ENTRY_PENDANT_INTENSITY: 18,
    PENDANT_DISTANCE: 5.0,
    PENDANT_ANGLE: Math.PI / 4.6,
    PENDANT_PENUMBRA: 0.82,
    PENDANT_DECAY: 1.55,
    PENDANT_LOCAL_FILL_INTENSITY: 1.8,
    PENDANT_LOCAL_FILL_DISTANCE: 2.0,
    BAR_WASH_INTENSITY: 28,
    BAR_WASH_DISTANCE: 5.6,
    BAR_WASH_ANGLE: Math.PI / 3.3,
    BAR_WASH_PENUMBRA: 0.90,
    BAR_WASH_DECAY: 1.45,
    PENDANT_SHADE_Y: 2.79,
    PENDANT_BULB_Y: 2.68,
    PENDANT_CEILING_Y: 3.65,
    TABLE_SHADOW_MAP_SIZE: 1024,
    PENDANT_SHADOW_MAP_SIZE: 512,
    SHADOW_BIAS: -0.00002,
    SHADOW_NORMAL_BIAS: 0.0
};

//CUE
export const CUE_RIG = {
    MIN_ELEVATION_DEG: 0,
    MAX_ELEVATION_DEG: 60,
    DEFAULT_ELEVATION_DEG: 4,
    DEFAULT_YAW_DEG: 180,
    TIP_GAP: 0.012,
    MIN_BACKSWING: 0.025,
    MAX_BACKSWING: 0.22,
    FORWARD_TRAVEL: 0.022,
    BACKSWING_SPEED: 0.34,
    MIN_STRIKE_SPEED: 0.55,
    MAX_STRIKE_SPEED: 3.20,
    RECOVERY_SPEED: 0.55,
    KEYBOARD_YAW_SPEED_DEG: 55,
    KEYBOARD_ELEVATION_SPEED_DEG: 28
};

//PLAYER VIEW
export const PLAYER_VIEW = {
    EYE_HEIGHT: 1.67,
    TABLE_MARGIN: 0.78,
    ORBIT_SPEED_RAD: 0.72,
    HEAD_YAW_LIMIT_DEG: 58,
    HEAD_PITCH_UP_LIMIT_DEG: 34,
    HEAD_PITCH_DOWN_LIMIT_DEG: 30,
    HEAD_YAW_SPEED_DEG: 58,
    HEAD_PITCH_SPEED_DEG: 44,
    AIM_DISTANCE_NEAR: 0.72,
    AIM_DISTANCE_FAR: 2.65,
    AIM_YAW_FREEDOM_NEAR_DEG: 72,
    AIM_YAW_FREEDOM_FAR_DEG: 18,
    AIM_ELEVATION_FAR_DEG: 20,
    POWER_MAX_FAR: 0.46,
    POWER_SWEEP_SPEED: 0.45,
    CONTACT_SPEED: 0.72,
    MOUSE_YAW_DEG_PER_PIXEL: 0.16,
    MOUSE_ELEVATION_DEG_PER_PIXEL: 0.12,
    AIM_CAMERA_BACK: 0.18,
    AIM_CAMERA_UP: 0.082,
    THREE_QUARTER_RISE: 0.27,
    THREE_QUARTER_BACK: 0.92,
    THREE_QUARTER_LOOK_AHEAD: 1.80,
    VIEW_OVERRIDE_SMOOTHING: 12.0,
    CPU_THINKING_VIEW_DURATION: 0.48,
    AIM_TRANSITION_DURATION: 0.55,
    BEV_RETURN_DURATION: 1.25,
    TURN_RETURN_DURATION: 0.95,
    SHOT_RETURN_DURATION: 0.72
};
export const CUE_CLEARANCE = {
    MARGIN: 0.003,
    BINARY_SEARCH_STEPS: 12,
    YAW_EPSILON_DEG: 0.05,
    ANGLE_MARGIN_DEG: 0.15
};

//PHYSICS
export const PHYSICS = {
    FIXED_DT: 1 / 240,
    MAX_FRAME_DT: 0.10,
    MAX_SUBSTEPS: 32,
    GRAVITY: 9.81,
    CONTACT_SLOP: 0.0004,
    SUPPORT_RAY_EXTRA: 0.025,
    REST_LINEAR_EPSILON: 0.002,
    REST_ANGULAR_EPSILON: 0.02,
    FALLEN_DEPTH: 0.35
};
export const TABLE_CONTACT = {
    RESTITUTION: 0.32,
    RESTITUTION_SPEED_THRESHOLD: 0.65,
    STATS_SPEED_THRESHOLD: 0.05
};
export const CLOTH = {
    SLIDING_FRICTION_COEFFICIENT: 0.20,
    ROLLING_RESISTANCE_COEFFICIENT: 0.034,
    ROLLING_CALIBRATION_SPEED: 1.0,
    ROLLING_CALIBRATION_STOP_DISTANCE: 1.5,
    ROLLING_CAPTURE_SPEED: 0.006,
    STOP_SPEED: 0.008,
    SIDE_SPIN_DAMPING: 0.35
};
export const POCKET = {
    UNSUPPORTED_ASSOCIATION_MARGIN_FACTOR: 0.80,
    SWEEP_SAMPLE_RADIUS_FRACTION: 0.20,
    MAX_SWEEP_SAMPLES: 16,
    COMMIT_LATERAL_MARGIN_FACTOR: 0.35,
    COMMIT_DEPTH_RADIUS_FACTOR: 0.70
};
export const POCKET_CAPTURE = {
    SWEEP_SAMPLE_RADIUS_FRACTION: 0.20,
    MAX_SWEEP_SAMPLES: 16,
    STOP_HORIZONTAL_SPEED_SCALE: 0.0
};
export const BALL_RETURN = {
    TARGET_INSET: 0.040,
    TARGET_CAPTURE_RADIUS: 0.008,
    ACCELERATION: 0.45,
    MAX_SPEED: 0.18,
    AXIS_SWITCH_TOLERANCE: 0.006,
    BALL_BLOCK_SLOP: 0.0005,
    FLOOR_SEARCH_START_DEPTH_RADIUS_FACTOR: 2.50
};
export const BALL_IN_HAND = {
    HEAD_STRING_EPSILON: 0.0005,
    EDGE_MARGIN: 0.0005,
    BALL_CLEARANCE: 0.0008,
    POCKET_MARGIN_RADIUS_FACTOR: 0.10
};

//TURN
export const TURN = {
    REARM_SETTLED_TIME: 0.25
};
export const CUSHION = {
    RESTITUTION: 0.82,
    RESTITUTION_SPEED_THRESHOLD: 0.05,
    TANGENTIAL_FRICTION_COEFFICIENT: 0.16,
    POSITION_SLOP: 0.00010,
    POSITION_CORRECTION_PERCENT: 0.95,
    ACTIVE_BELOW_CLOTH_RADIUS_FACTOR: 0.35
};
export const BALL_COLLISION = {
    RESTITUTION: 0.93,
    RESTITUTION_SPEED_THRESHOLD: 0.08,
    TANGENTIAL_FRICTION_COEFFICIENT: 0.05,
    TANGENTIAL_SPEED_EPSILON: 0.0005,
    POSITION_SLOP: 0.00010,
    POSITION_CORRECTION_PERCENT: 0.82,
    SOLVER_ITERATIONS: 5
};

//RACK
export const RACK = {
    OBJECT_BALL_COUNT: 15,
    BALL_GAP: 0.00020,
    APEX_Z_FRACTION: -0.18
};
export const TRAJECTORY_HELPER = {
    ENABLED_BY_DEFAULT: true,
    MAX_SIMULATION_TIME: 7.0,
    SAMPLE_EVERY_STEPS: 4,
    MIN_REBUILD_INTERVAL: 0.10,
    MAX_COLLISION_MARKERS: 24,
    VISUAL_Y_OFFSET: 0.0015
};
export const CPU_PLAYER = {
    PLAYER_INDEX: 1,
    THINK_DELAY: 0.45,
    AIM_REVIEW_DELAY: 0.40,
    NEXT_SHOT_DELAY: 0.35,
    FALLBACK_MIN_POWER: 0.34,
    FALLBACK_MAX_POWER: 0.72,
    PLACEMENT_GRID_FRACTIONS: [
        0.50,
        0.35,
        0.65,
        0.20,
        0.80
    ]
};
export const BOT_PLANNER = {
    MAX_SIMULATION_TIME: 4.5,
    MAX_GEOMETRIC_ROUTES: 5,
    MAX_FALLBACK_TARGETS: 4,
    AIM_OFFSETS_DEG: [-0.45, 0, 0.45],
    POWER_FACTORS: [0.90, 1.06],
    BREAK_AIM_OFFSETS_DEG: [-1.5, -0.75, 0, 0.75, 1.5],
    BREAK_POWERS: [0.78, 0.90, 1.00],
    MIN_CUT_COSINE: 0.14,
    OBSTACLE_CLEARANCE: 0.0015,
    YIELD_EVERY_CANDIDATES: 1,
    TOP_RESULTS_TO_KEEP: 5
};

//SHOT
export const SHOT = {
    DEFAULT_POWER: 0.35,
    MIN_POWER: 0.05,
    MAX_POWER: 1.0,
    MAX_BALL_SPEED: 4.5,
    MAX_NORMALIZED_HIT_RADIUS: 0.82,
    DEFAULT_HIT_U: 0,
    DEFAULT_HIT_V: 0
};
