//EVENT TYPES
export const EventType = Object.freeze({
    SHOT_STARTED: "SHOT_STARTED",
    BALL_CONTACT: "BALL_CONTACT",
    RAIL_CONTACT: "RAIL_CONTACT",
    POCKET_ENTRY: "POCKET_ENTRY",
    BALL_POCKETED: "BALL_POCKETED",
    SHOT_ENDED: "SHOT_ENDED"
});
